export {
  createClient,
  ApiError,
  type SeedvaultClient,
  type FileEntry,
  type PutFileOptions,
  type SearchResult,
  type SearchOptions,
  type SearchResponse,
  type ActivityEvent,
  type ActivityOptions,
  type ActivityResponse,
  type HealthResponse,
  type SubscribeOptions,
  type VaultEvent,
} from "@seedvault/sdk";
