export {
  createClient,
  ApiError,
  parseVaultEvent,
  matchesFilter,
  type SeedvaultClient,
  type FileEntry,
  type PutFileOptions,
  type SearchResult,
  type SearchOptions,
  type SearchResponse,
  type ActivityEvent,
  type ActivityOptions,
  type ActivityResponse,
  type HealthResponse,
  type SubscribeOptions,
  type VaultEvent,
  type VaultEventType,
  type FileUpdatedEvent,
  type FileDeletedEvent,
  type ActivityVaultEvent,
} from "@seedvault/sdk";
